### ISSUE TITLE
Handle ties better

### ISSUE THREAD

**Issue by shaycrk** [dssg/lorax#5]
The helper methods `top_k_example_ids` and `bottom_k_example_ids` don't attempt to handle ties in scores at the cut-off but definitely should do so (and do so in a way consistent with what's done for model evaluation in `catwalk`)

**Comment by hakoenig** [comment]
When comparing with https://github.com/dssg/triage/blob/master/src/triage/component/catwalk/evaluation.py#L14, we are already getting the same behavior.
